Resources/ClappersCars/ClappersCars/Controllers/UserRequestFormsController.cs
using ClappersCars.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClappersCars.Controllers
{
    public class UserRequestFormsController : Controller
    {
        private ClappersCarsContext db = new ClappersCarsContext();

        // GET: UserRequestForms
        [Authorize]
        public ActionResult Index()
        {
            var userRequestForms = db.UserRequestForms.Include(u => u.Vehicle);
            return View(userRequestForms.ToList());
        }


        // GET: UserRequestForms/Create
        public ActionResult Create()
        {
            ViewBag.VehicleID = new SelectList(db.Vehicles, "VehicleID", "Make");
            return View();
        }

        // POST: UserRequestForms/Create
        [HttpPost]
        public ActionResult Create(UserRequestForm userRequestForm)
        {
            if (ModelState.IsValid)
            {
                db.UserRequestForms.Add(userRequestForm);
                db.SaveChanges();
                return RedirectToAction("Index", "Vehicles");
            }

            ViewBag.VehicleID = new SelectList(db.Vehicles, "VehicleID", "Make", userRequestForm.VehicleID);
            return View(userRequestForm);
        }

        // GET: UserRequestForms/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRequestForm userRequestForm = db.UserRequestForms.Find(id);
            if (userRequestForm == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleID = new SelectList(db.Vehicles, "VehicleID", "Make", userRequestForm.VehicleID);
            return View(userRequestForm);
        }

        // POST: UserRequestForms/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(UserRequestForm userRequestForm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userRequestForm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VehicleID = new SelectList(db.Vehicles, "VehicleID", "Make", userRequestForm.VehicleID);
            return View(userRequestForm);
        }

        // GET: UserRequestForms/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRequestForm userRequestForm = db.UserRequestForms.Find(id);
            if (userRequestForm == null)
            {
                return HttpNotFound();
            }
            return View(userRequestForm);
        }

        // POST: UserRequestForms/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserRequestForm userRequestForm = db.UserRequestForms.Find(id);
            db.UserRequestForms.Remove(userRequestForm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Resources/ClappersCars/ClappersCars/Views/Shared/Details.cshtml
@model ClappersCars.Models.Vehicle

<div class="modal fade" id="details-@Model.VehicleID" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <div>
                    <h4>Vehicle</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Make)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Make)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Model)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Model)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Year)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Year)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Mileage)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Mileage)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.AdTitle)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AdTitle)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Price)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.UrlOfPicture)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.UrlOfPicture)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.IsAvailable)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.IsAvailable)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Condition)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Condition)
                        </dd>

                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                @Html.ActionLink("Request", "Create","UserRequestForms", new { id = Model.VehicleID },new {@class="btn btn-default"})
            </div>
        </div>
    </div>
</div>



<h2>Details</h2>

<p>
    @Html.ActionLink("Return", "Index")
</p>

Resources/ClappersCars/ClappersCars/Views/Shared/UserRequestDetails.cshtml
@using ClappersCars.Models
@model ClappersCars.Models.UserRequestForm


<div class="modal fade" id="userrequestdetails-@Model.UserRequestFormID" tabindex="-1" role="dialog" aria-labelledby="userrequestDetails">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">User Request Details</h4>
            </div>
            <div class="modal-body">
                <div>
                    
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Vehicle.Make)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Vehicle.Make)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Phone)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Phone)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.BestTimeToCall)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.BestTimeToCall)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.PreferredContactMethod)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.PreferredContactMethod)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TimeframeToPurchaseStart)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TimeframeToPurchaseStart)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TimeframeToPurchaseEnd)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TimeframeToPurchaseEnd)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.AdditionalInformation)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AdditionalInformation)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.LastContactDate)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.LastContactDate)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.StatusOfRequest)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.StatusOfRequest)
                        </dd>

                    </dl>
                </div>
            </div>
            <div class="modal-footer">
             
                   <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                   @Html.ActionLink("Edit Request", "Edit", "UserRequestForms", new {id = Model.VehicleID}, new {@class = "btn btn-default"})
          

            </div>
        </div>
    </div>
</div>

Resources/ClappersCars/ClappersCars/Views/Shared/VehicleDetails.cshtml
@model ClappersCars.Models.Vehicle

<div class="modal fade" id="vehicledetails-@Model.VehicleID" tabindex="-1" role="dialog" aria-labelledby="VehicleDetails">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Vehicle Details</h4>
            </div>
            <div class="modal-body">
                <div>
                    
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Make)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Make)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Model)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Model)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Year)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Year)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Mileage)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Mileage)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.AdTitle)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AdTitle)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Price)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.UrlOfPicture)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.UrlOfPicture)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.IsAvailable)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.IsAvailable)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Condition)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Condition)
                        </dd>

                    </dl>
                </div>
            </div>
        
        </div>
    </div>
</div>

Resources/ClappersCars/ClappersCars/Views/Shared/_CreateUserRequestForm.cshtml
@using ClappersCars.Models
@model ClappersCars.Models.UserRequestForm

<div class="modal fade" ID="CreateUserRequestForm-@Model.VehicleID" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">User Request Form</h4>
            </div>
            <div class="modal-body">

                @using (Html.BeginForm("Create", "UserRequestForms"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(m => m.VehicleID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.BestTimeToCall, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EnumDropDownListFor(model => model.BestTimeToCall, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.BestTimeToCall, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PreferredContactMethod, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EnumDropDownListFor(model => model.PreferredContactMethod, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.PreferredContactMethod, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TimeframeToPurchaseStart, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.TimeframeToPurchaseStart, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TimeframeToPurchaseStart.Date, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TimeframeToPurchaseEnd, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.TimeframeToPurchaseEnd, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TimeframeToPurchaseEnd.Date, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.AdditionalInformation, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AdditionalInformation, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AdditionalInformation, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.Hidden("LastContactDate", DateTime.Now)
                        @Html.Hidden("StatusOfRequest", ResponseStatus.New)
                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9">
                            </div>
                            <div class="modal-footer">
                                <input type="submit" value="Create" class="btn btn-default" />
                                
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                }
                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

Resources/ClappersCars/ClappersCars/Views/Shared/_CreateVehicles.cshtml
@model ClappersCars.Models.Vehicle

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Vehicle</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Mileage, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Mileage, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Mileage, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.AdTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.AdTitle, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AdTitle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrlOfPicture, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrlOfPicture, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UrlOfPicture, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.IsAvailable)
                                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Condition, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Condition)
                                    @Html.ValidationMessageFor(model => model.Condition, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

Resources/ClappersCars/ClappersCars/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clappers Cars, LLC.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Clappers Cars", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Vehicles", "Index", "Vehicles")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Request", "Index", "UserRequestForms")</li>


                    }
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Clappers Cars, LLC.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>